import type { Team } from "@/lib/types";
import { teamLogoPath, teamWhiteLogoPath } from "@/lib/team-logos";

export const fanSiteHosts = [
  "t1",
  "geng",
  "hle",
  "dk",
  "kt",
  "drx",
  "ns",
  "bro",
  "fox",
  "soop",
] as const;

export type FanSiteHost = (typeof fanSiteHosts)[number];

export const teams: Team[] = [
  {
    id: "team_t1",
    slug: "t1",
    name: "T1",
    shortName: "T1",
    logoUrl: teamLogoPath("t1"),
    logoWhiteUrl: teamWhiteLogoPath("t1"),
    backgroundUrl: "/teams/t1/bg.jpg",
    primaryColor: "#E4002B",
    secondaryColor: "#111111",
    fanSiteHost: "t1",
    officialHomepageUrl: "https://t1.gg",
    officialYoutubeUrl: "https://www.youtube.com/@T1LoL",
    officialXUrl: "https://x.com/T1LoL",
    officialInstagramUrl: "https://www.instagram.com/t1lol",
  },
  {
    id: "team_geng",
    slug: "geng",
    name: "Gen.G",
    shortName: "GEN",
    logoUrl: teamLogoPath("geng"),
    logoWhiteUrl: teamWhiteLogoPath("geng"),
    backgroundUrl: "/teams/geng/bg.jpg",
    primaryColor: "#AA8A00",
    secondaryColor: "#000000",
    fanSiteHost: "geng",
    officialHomepageUrl: "https://geng.gg",
    officialYoutubeUrl: "https://www.youtube.com/@GenGEsports",
    officialXUrl: "https://x.com/GenG_KR",
    officialInstagramUrl: "https://www.instagram.com/gengesports",
  },
  {
    id: "team_hle",
    slug: "hle",
    name: "Hanwha Life Esports",
    shortName: "HLE",
    logoUrl: teamLogoPath("hle"),
    logoWhiteUrl: teamWhiteLogoPath("hle"),
    backgroundUrl: "/teams/hle/bg.jpg",
    primaryColor: "#F37321",
    secondaryColor: "#1F2933",
    fanSiteHost: "hle",
    officialHomepageUrl: "https://www.hanwhaeagles.co.kr",
    officialYoutubeUrl: "https://www.youtube.com/@HanwhaLifeEsports",
    officialXUrl: "https://x.com/HLEofficial",
    officialInstagramUrl: "https://www.instagram.com/hle.official",
  },
  {
    id: "team_dk",
    slug: "dk",
    name: "Dplus KIA",
    shortName: "DK",
    logoUrl: teamLogoPath("dk"),
    logoWhiteUrl: teamWhiteLogoPath("dk"),
    backgroundUrl: "/teams/dk/bg.jpg",
    primaryColor: "#00A3E0",
    secondaryColor: "#0A0F1F",
    fanSiteHost: "dk",
    officialHomepageUrl: "https://dpluskia.gg",
    officialYoutubeUrl: "https://www.youtube.com/@DplusKIA",
    officialXUrl: "https://x.com/DplusKIA",
    officialInstagramUrl: "https://www.instagram.com/dpluskia",
  },
  {
    id: "team_kt",
    slug: "kt",
    name: "KT Rolster",
    shortName: "KT",
    logoUrl: teamLogoPath("kt"),
    logoWhiteUrl: teamWhiteLogoPath("kt"),
    backgroundUrl: "/teams/kt/bg.jpg",
    primaryColor: "#ED1C24",
    secondaryColor: "#0E0E0E",
    fanSiteHost: "kt",
    officialHomepageUrl: "https://www.ktrolster.com",
    officialYoutubeUrl: "https://www.youtube.com/@KTRolster",
    officialXUrl: "https://x.com/KTRolster_tw",
    officialInstagramUrl: "https://www.instagram.com/ktrolster",
  },
  {
    id: "team_drx",
    slug: "drx",
    name: "DRX",
    shortName: "DRX",
    logoUrl: teamLogoPath("drx"),
    logoWhiteUrl: teamWhiteLogoPath("drx"),
    backgroundUrl: "/teams/drx/bg.jpg",
    primaryColor: "#5C88DA",
    secondaryColor: "#101828",
    fanSiteHost: "drx",
    officialHomepageUrl: "https://drx.gg",
    officialYoutubeUrl: "https://www.youtube.com/@DRXGlobal",
    officialXUrl: "https://x.com/DRXGlobal",
    officialInstagramUrl: "https://www.instagram.com/drxglobal",
    identityHistory: [
      {
        id: "identity_drx_current",
        teamId: "team_drx",
        name: "DRX",
        shortName: "DRX",
        slug: "drx",
        logoUrl: teamLogoPath("drx"),
        effectiveFrom: "2026-01-01",
        note: "현재 공개 표시값",
      },
      {
        id: "identity_drx_krx_example",
        teamId: "team_drx",
        name: "Kiwoom DRX",
        shortName: "KRX",
        slug: "krx",
        logoUrl: teamLogoPath("drx"),
        sponsorName: "키움증권",
        effectiveFrom: "2026-07-01",
        note: "키움증권 네이밍 후 KRX로 표기. 팬 사이트 호스트와 로고는 drx 유지",
      },
    ],
  },
  {
    id: "team_ns",
    slug: "ns",
    name: "Nongshim RedForce",
    shortName: "NS",
    logoUrl: teamLogoPath("ns"),
    logoWhiteUrl: teamWhiteLogoPath("ns"),
    backgroundUrl: "/teams/ns/bg.jpg",
    primaryColor: "#D71920",
    secondaryColor: "#16213E",
    fanSiteHost: "ns",
    officialHomepageUrl: "https://redforce.gg",
    officialYoutubeUrl: "https://www.youtube.com/@NSRedForce",
    officialXUrl: "https://x.com/NS_RedForce",
    officialInstagramUrl: "https://www.instagram.com/ns_redforce",
  },
  {
    id: "team_bro",
    slug: "bro",
    name: "OKSavingsBank BRION",
    shortName: "BRO",
    logoUrl: teamLogoPath("bro"),
    logoWhiteUrl: teamWhiteLogoPath("bro"),
    backgroundUrl: "/teams/bro/bg.jpg",
    primaryColor: "#C89B3C",
    secondaryColor: "#1B1B1B",
    fanSiteHost: "bro",
    officialHomepageUrl: "https://brionesports.gg",
    officialYoutubeUrl: "https://www.youtube.com/@BRIONEsports",
    officialXUrl: "https://x.com/Brionesports",
    officialInstagramUrl: "https://www.instagram.com/brionesports",
  },
  {
    id: "team_fox",
    slug: "fox",
    name: "BNK FearX",
    shortName: "FOX",
    logoUrl: teamLogoPath("fox"),
    logoWhiteUrl: teamWhiteLogoPath("fox"),
    backgroundUrl: "/teams/fox/bg.jpg",
    primaryColor: "#F05A28",
    secondaryColor: "#12263A",
    fanSiteHost: "fox",
    officialHomepageUrl: "https://fearx.gg",
    officialYoutubeUrl: "https://www.youtube.com/@FearX",
    officialXUrl: "https://x.com/BNKFEARX",
    officialInstagramUrl: "https://www.instagram.com/bnkfearx",
  },
  {
    id: "team_soop",
    slug: "soop",
    name: "SOOP",
    shortName: "SOOP",
    logoUrl: teamLogoPath("soop"),
    logoWhiteUrl: teamWhiteLogoPath("soop"),
    backgroundUrl: "/teams/soop/bg.jpg",
    primaryColor: "#1E88E5",
    secondaryColor: "#041A2F",
    fanSiteHost: "soop",
    officialHomepageUrl: "https://freecs.gg",
    officialYoutubeUrl: "https://www.youtube.com/@Freecs",
    officialXUrl: "https://x.com/freecs_lol",
    officialInstagramUrl: "https://www.instagram.com/freecs_official",
  },
];

export const teamSlugs = teams.map((team) => team.slug);

export function getTeamBySlug(slug: string) {
  return teams.find((team) => team.slug === slug);
}

export function getTeamByFanSiteHost(host: string) {
  return teams.find((team) => team.fanSiteHost === host);
}

export function getTeamByRouteKey(value: string) {
  return teams.find((team) => team.slug === value || team.fanSiteHost === value);
}

export function getTeamById(id: string) {
  return teams.find((team) => team.id === id);
}
