import { useRouter } from 'expo-router';
import ArrowLeft from 'lucide-react-native/icons/arrow-left';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import type { MobileBootstrapDto, MobileMeDto, MobileNotificationPreferences, MobileTeamSummary } from '../../../packages/contracts/src/mobile-v1';
import { fetchMobileApi, mutateMobileApi } from '@/lib/api-client';
import { useMinionTheme } from '@/hooks/use-minion-theme';
import { useAuth } from '@/providers/auth-provider';

export default function SettingsScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const { fonts, showToast, theme } = useMinionTheme(); const { refreshViewer, session } = useAuth();
  const [data, setData] = useState<MobileMeDto | null>(null); const [nickname, setNickname] = useState(''); const [saving, setSaving] = useState(false);
  const [teams, setTeams] = useState<MobileTeamSummary[]>([]);
  const load = useCallback(async () => { const [next, bootstrap] = await Promise.all([fetchMobileApi<MobileMeDto>('/api/mobile/v1/me'), fetchMobileApi<MobileBootstrapDto>('/api/mobile/v1/bootstrap')]); setData(next); setTeams(bootstrap.teams); setNickname(next.profile.nickname ?? ''); }, []);
  useEffect(() => { if (!session) router.replace('/login?next=/me/settings'); else void load(); }, [load, router, session]);
  const save = async (payload: unknown, success: string) => { setSaving(true); try { const next = await mutateMobileApi<MobileMeDto>('/api/mobile/v1/me', 'PATCH', payload); setData(next); setNickname(next.profile.nickname ?? ''); await refreshViewer(); showToast(success, 'success'); } catch (error) { showToast(error instanceof Error ? error.message : '저장하지 못했습니다.', 'error'); } finally { setSaving(false); } };
  if (!data) return <View style={[styles.center, { backgroundColor: theme.pageBackground }]}><ActivityIndicator color={theme.accent} size="large" /></View>;
  const togglePreference = (key: keyof MobileNotificationPreferences) => void save({ notificationPreferences: { ...data.notificationPreferences, [key]: !data.notificationPreferences[key] } }, '알림 설정을 저장했습니다.');
  const followed = new Set(data.profile.followedTeamIds);
  return <View style={{ backgroundColor: theme.pageBackground, flex: 1 }}><View style={[styles.header, { borderBottomColor: theme.border, paddingTop: insets.top }]}><Pressable onPress={() => router.back()} style={styles.icon}><ArrowLeft color={theme.ink} size={22} /></Pressable><Text style={{ color: theme.ink, fontFamily: fonts.display, fontSize: 17 }}>내 설정</Text></View><ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 28 }]}>
    <Card title="프로필"><Text style={[styles.label, { color: theme.muted, fontFamily: fonts.bold }]}>닉네임</Text><View style={styles.row}><TextInput maxLength={16} onChangeText={setNickname} style={[styles.input, { borderColor: theme.border, color: theme.ink, fontFamily: fonts.regular }]} value={nickname} /><Pressable disabled={saving} onPress={() => void save({ nickname }, '프로필을 저장했습니다.')} style={[styles.save, { backgroundColor: theme.accent }]}><Text style={{ color: '#061018', fontFamily: fonts.bold }}>저장</Text></Pressable></View><Text style={{ color: theme.muted, fontFamily: fonts.medium, fontSize: 12 }}>{data.profile.email} · {data.profile.authProvider ?? 'email'}</Text></Card>
    <Card title="최애팀·팔로우 팀"><View style={styles.teams}>{teams.map((team) => { const favorite = data.profile.favoriteTeamId === team.id; const isFollowed = followed.has(team.id); return <View key={team.id} style={[styles.teamRow, { borderBottomColor: theme.divider }]}><Text style={{ color: theme.ink, flex: 1, fontFamily: fonts.bold }}>{team.shortName}</Text><Pressable onPress={() => void save({ followedTeamIds: isFollowed ? [...followed].filter((id) => id !== team.id) : [...followed, team.id] }, '팔로우 팀을 저장했습니다.')} style={[styles.pill, { backgroundColor: isFollowed ? theme.surfaceMuted : 'transparent', borderColor: theme.border }]}><Text style={{ color: theme.text, fontFamily: fonts.bold, fontSize: 12 }}>{isFollowed ? '팔로잉' : '팔로우'}</Text></Pressable><Pressable onPress={() => void save({ favoriteTeamId: favorite ? null : team.id }, '최애팀을 저장했습니다.')} style={[styles.pill, { backgroundColor: favorite ? theme.accent : 'transparent', borderColor: favorite ? theme.accent : theme.border }]}><Text style={{ color: favorite ? '#061018' : theme.text, fontFamily: fonts.bold, fontSize: 12 }}>{favorite ? '최애팀' : '최애 설정'}</Text></Pressable></View>; })}</View></Card>
    <Card title="알림"><Toggle label="앱 내 알림" onChange={() => togglePreference('inAppEnabled')} value={data.notificationPreferences.inAppEnabled} /><Toggle label="경기 시작" onChange={() => togglePreference('matchStartEnabled')} value={data.notificationPreferences.matchStartEnabled} /><Toggle label="주요 경기 이벤트" onChange={() => togglePreference('matchEventsEnabled')} value={data.notificationPreferences.matchEventsEnabled} /><Toggle label="평점 오픈" onChange={() => togglePreference('ratingOpenEnabled')} value={data.notificationPreferences.ratingOpenEnabled} /></Card>
    <Card title={`차단 관리 ${data.blockedUsers.length ? `(${data.blockedUsers.length})` : ''}`}>{data.blockedUsers.length === 0 ? <Text style={{ color: theme.muted, fontFamily: fonts.medium, paddingVertical: 8 }}>차단한 사용자가 없습니다.</Text> : data.blockedUsers.map((user) => <View key={user.id} style={[styles.teamRow, { borderBottomColor: theme.divider }]}><Text style={{ color: theme.ink, flex: 1, fontFamily: fonts.bold }}>{user.nickname}</Text><Pressable onPress={() => void save({ unblockUserId: user.id }, '차단을 해제했습니다.')}><Text style={{ color: '#dc2626', fontFamily: fonts.bold, fontSize: 13 }}>차단 해제</Text></Pressable></View>)}</Card>
  </ScrollView></View>;
}
function Card({ children, title }: { children: React.ReactNode; title: string }) { const { fonts, theme } = useMinionTheme(); return <View style={[styles.card, { backgroundColor: theme.surface, borderColor: theme.border }]}><Text style={{ color: theme.ink, fontFamily: fonts.black, fontSize: 17 }}>{title}</Text>{children}</View>; }
function Toggle({ label, onChange, value }: { label: string; onChange: () => void; value: boolean }) { const { fonts, theme } = useMinionTheme(); return <View style={[styles.toggle, { borderBottomColor: theme.divider }]}><Text style={{ color: theme.text, flex: 1, fontFamily: fonts.medium }}>{label}</Text><Switch onValueChange={onChange} trackColor={{ false: theme.border, true: theme.accent }} value={value} /></View>; }
const styles = StyleSheet.create({ center: { alignItems: 'center', flex: 1, justifyContent: 'center' }, header: { alignItems: 'center', borderBottomWidth: 1, flexDirection: 'row', minHeight: 56, paddingHorizontal: 8 }, icon: { alignItems: 'center', height: 44, justifyContent: 'center', width: 44 }, content: { gap: 14, padding: 16 }, card: { borderRadius: 16, borderWidth: 1, gap: 12, padding: 18 }, label: { fontSize: 12 }, row: { flexDirection: 'row', gap: 8 }, input: { borderRadius: 10, borderWidth: 1, flex: 1, minHeight: 44, paddingHorizontal: 12 }, save: { alignItems: 'center', borderRadius: 10, justifyContent: 'center', paddingHorizontal: 16 }, teams: { marginTop: -2 }, teamRow: { alignItems: 'center', borderBottomWidth: 1, flexDirection: 'row', gap: 8, minHeight: 52 }, pill: { borderRadius: 9, borderWidth: 1, paddingHorizontal: 9, paddingVertical: 7 }, toggle: { alignItems: 'center', borderBottomWidth: 1, flexDirection: 'row', minHeight: 54 } });
