begin;
-- Run inside a transaction with the migration loaded; always roll back test writes.
do $test$
declare pid uuid; human uuid:=gen_random_uuid(); newer uuid:=gen_random_uuid(); ai uuid;
 e public.community_ai_studio_inbox; old_job public.community_ai_studio_inbox; job public.community_ai_studio_inbox;
 answer uuid; views_before integer; version_before bigint;
begin
 select post_id into pid from public.community_ai_studio_campaigns limit 1;
 if pid is null then raise exception 'Missing studio test fixture'; end if;
 select id into ai from auth.users where raw_app_meta_data->>'community_studio_persona_id'='neutral-analyst' limit 1;
 update public.community_ai_studio_campaigns set auto_reply_enabled=false;
 update public.community_ai_studio_campaigns set state='active',auto_reply_enabled=true where post_id=pid;
 update public.community_posts set deleted_at=null,blinded_at=null where id=pid;
 update public.community_ai_studio_settings set watch_enabled=true where singleton;
 insert into public.community_comments(id,post_id,guest_key,guest_nickname,content) values(human,pid,'auto-test-'||gen_random_uuid(),'검증 유저','이번 경기는 어떻게 봄?');
 select * into e from public.community_ai_studio_inbox where post_id=pid;
 if e.comment_id<>human or e.status<>'pending' then raise exception 'Human event not captured'; end if;
 update public.community_ai_studio_inbox set retry_at=now() where id=e.id;
 select * into old_job from public.community_ai_studio_claim_replies(1);
 if old_job.id is null then raise exception 'Claim missing'; end if;
 if exists(select 1 from public.community_ai_studio_claim_replies(1)) then raise exception 'Duplicate lease'; end if;
 insert into public.community_comments(id,post_id,guest_key,guest_nickname,content) values(newer,pid,'auto-test-'||gen_random_uuid(),'검증 유저','아 방금 밴픽 얘기한 거임');
 if public.community_ai_studio_finish_reply(old_job.id,old_job.activity_version,old_job.generation_token) then raise exception 'Stale completion accepted'; end if;
 select * into e from public.community_ai_studio_inbox where post_id=pid;
 if e.comment_id<>newer or e.activity_version<=old_job.activity_version then raise exception 'Latest target not updated'; end if;
 update public.community_ai_studio_inbox set retry_at=now() where id=e.id;
 select * into job from public.community_ai_studio_claim_replies(1);
 update public.community_ai_studio_inbox set status='drafted',context_hash='test-hash',response_persona='neutral-analyst',response_text='밴픽은 그럴 수 있지' where id=job.id;
 if not public.community_ai_studio_finish_reply(job.id,job.activity_version,job.generation_token,ai,'neutral-analyst','밴픽은 그럴 수 있지','test-hash') then raise exception 'Completion failed'; end if;
 select approved_comment_id into answer from public.community_ai_studio_inbox where id=job.id;
 if not exists(select 1 from public.community_ai_studio_queue where id=answer and status='scheduled' and parent_id=newer) then raise exception 'Wrong reply reservation'; end if;
 -- An edit before publication also invalidates the reservation.
 update public.community_comments set content='수정한 밴픽 의견' where id=newer;
 if (select status from public.community_ai_studio_queue where id=answer)<>'cancelled' then raise exception 'Stale reservation survived edit'; end if;
 update public.community_ai_studio_inbox set retry_at=now() where id=e.id;
 select * into job from public.community_ai_studio_claim_replies(1);
 if not public.community_ai_studio_finish_reply(job.id,job.activity_version,job.generation_token,p_error=>'temporary model failure') then raise exception 'Retry not saved'; end if;
 if not exists(select 1 from public.community_ai_studio_inbox where id=job.id and status='pending' and generation_token is null and retry_at>now() and last_error is not null) then raise exception 'Retry fields incorrect'; end if;
 update public.community_ai_studio_inbox set retry_at=now() where id=e.id;
 select * into job from public.community_ai_studio_claim_replies(1);
 perform public.community_ai_studio_control(pid,'pause');
 if public.community_ai_studio_finish_reply(job.id,job.activity_version,job.generation_token) then raise exception 'Manual pause bypassed'; end if;
 if exists(select 1 from public.community_ai_studio_claim_replies(1)) then raise exception 'Paused campaign claimed'; end if;
 perform public.community_ai_studio_control(pid,'resume');
 select * into job from public.community_ai_studio_claim_replies(1);
 update public.community_ai_studio_inbox set status='drafted',context_hash='test-hash',response_persona='neutral-analyst',response_text='밴픽 얘기였구나' where id=job.id;
 perform public.community_ai_studio_finish_reply(job.id,job.activity_version,job.generation_token,ai,'neutral-analyst','밴픽 얘기였구나','test-hash');
 select approved_comment_id,activity_version into answer,version_before from public.community_ai_studio_inbox where id=job.id;
 update public.community_ai_studio_queue set due_at=now() where id=answer;
 select view_count into views_before from public.community_posts where id=pid;
 perform public.community_ai_studio_tick();
 if not exists(select 1 from public.community_comments where id=answer) then raise exception 'Automatic reply not published'; end if;
 if (select view_count from public.community_posts where id=pid)<>views_before+1 then raise exception 'AI view count incorrect'; end if;
 if not exists(select 1 from public.community_ai_studio_inbox where id=job.id and status='approved' and activity_version=version_before) then raise exception 'AI triggered regeneration loop'; end if;
 insert into public.community_comments(post_id,guest_key,guest_nickname,content) values(pid,'auto-test-'||gen_random_uuid(),'검증 유저','그럼 다음 세트는?');
 if not exists(select 1 from public.community_ai_studio_inbox where id=job.id and status='pending' and activity_version>version_before) then raise exception 'Second human turn not reopened'; end if;
 update public.community_ai_studio_inbox set retry_at=now() where id=e.id;
 select * into job from public.community_ai_studio_claim_replies(1);
 update public.community_ai_studio_inbox set lease_until=now()-interval '1 second' where id=e.id;
 select * into old_job from public.community_ai_studio_claim_replies(1);
 if old_job.generation_token=job.generation_token then raise exception 'Expired lease not recovered'; end if;
 if public.community_ai_studio_finish_reply(job.id,job.activity_version,job.generation_token) then raise exception 'Expired worker completed'; end if;
 if not public.community_ai_studio_finish_reply(old_job.id,old_job.activity_version,old_job.generation_token) then raise exception 'No reply decision failed'; end if;
 if exists(select 1 from public.community_ai_studio_claim_replies(1)) then raise exception 'No reply decision loops'; end if;
 if has_function_privilege('anon','public.community_ai_studio_claim_replies(integer)','EXECUTE') or has_function_privilege('authenticated','public.community_ai_studio_finish_reply(uuid,bigint,uuid,uuid,text,text,text,text)','EXECUTE') then raise exception 'Public worker access'; end if;
end $test$;
rollback;
