-- Add Korean phonetic / nickname aliases so search matches "페이커" as well as "faker".
-- Player/team in-game names are stored in English only, so Korean-language queries
-- (the common case for this fandom) never matched. These aliases bridge that gap.

alter table public.players add column if not exists search_aliases text[] not null default '{}';
alter table public.teams add column if not exists search_aliases text[] not null default '{}';

-- Players: Korean reading of the in-game name, plus the Korean real name for
-- players whose Korean name is widely known.
update public.players p
set search_aliases = v.aliases
from (values
  -- BNK FEARX
  ('clear', array['클리어','송현민']),
  ('daystar', array['데이스타','유지명']),
  ('fiesta', array['피에스타','안현서']),
  ('kellin', array['켈린','김형규']),
  ('raptor', array['랩터','전어진']),
  ('slayer', array['슬레이어','김진영']),
  ('taeyoon', array['태윤','김태윤']),
  ('vicla', array['비클라','이대광']),
  -- BRO
  ('casting', array['캐스팅','신민제']),
  ('gideon', array['기디언','김민성']),
  ('namgung', array['남궁','남궁성훈']),
  ('roamer', array['로머','조우진']),
  ('teddy', array['테디','박진성']),
  -- DK
  ('career', array['커리어','오형석']),
  ('lucid', array['루시드','최용혁']),
  ('showmaker', array['쇼메이커','쇼메','허수']),
  ('siwoo', array['시우','전시우']),
  ('smash', array['스매시','김용주']),
  -- DNS (수퍼스)
  ('clozer', array['클로저','이주현']),
  ('ddoiv', array['또이브','방문영']),
  ('deokdam', array['덕담','서대길']),
  ('dudu', array['두두','이동주']),
  ('enosh', array['에노쉬','에노시','곽규준']),
  ('life', array['라이프','김정민']),
  ('peter', array['피터','정윤수']),
  ('pyosik', array['표식','홍창현']),
  ('quantum', array['퀀텀','손정환']),
  ('sharvel', array['샤르벨','김단우']),
  -- GEN
  ('canyon', array['캐니언','김건부']),
  ('chovy', array['쵸비','초비','정지훈']),
  ('duro', array['두로','주민규']),
  ('kiin', array['기인','김기인']),
  ('ruler', array['룰러','박재혁']),
  -- HLE
  ('bluffing', array['블러핑','박규용']),
  ('delight', array['딜라이트','유환중']),
  ('gumayusi', array['구마유시','구마','이민형']),
  ('kanavi', array['카나비','서진혁']),
  ('zeka', array['제카','김건우']),
  ('zeus', array['제우스','최우제']),
  -- KIWOOM DRX
  ('andil', array['안딜','문관빈']),
  ('jiwoo', array['지우','정지우']),
  ('lazyfeel', array['레이지필']),
  ('rich', array['리치','이재원']),
  ('ucal', array['유칼','손우현']),
  ('vincenzo', array['빈센조','하승민']),
  ('willer', array['윌러','김정현']),
  -- KT
  ('aiming', array['에이밍','김하람']),
  ('bdd', array['비디디','곽보성']),
  ('cuzz', array['커즈','문우찬']),
  ('effort', array['에포트','이상호']),
  ('fenrir', array['펜리르','박강준']),
  ('ghost', array['고스트','장용준']),
  ('perfect', array['퍼펙트','이승민']),
  ('pollu', array['폴루','오동규']),
  -- NS 레드포스
  ('calix', array['칼릭스','신현빈']),
  ('diable', array['디아블','남대근']),
  ('kingen', array['킹겐','황성훈']),
  ('lehends', array['레핸즈','손시우']),
  ('pleata', array['플레타','손민우']),
  ('scout', array['스카웃','스카우트','이예찬']),
  ('sponge', array['스펀지','배영준']),
  -- T1
  ('doran', array['도란','최현준']),
  ('faker', array['페이커','페커','이상혁']),
  ('keria', array['케리아','류민석']),
  ('oner', array['오너','문현준']),
  ('peyz', array['페이즈','김수환']),
  -- International / import teams (Korean reading of in-game name)
  ('flandre', array['플랑드르']),
  ('hope', array['호프']),
  ('kael', array['카엘','김진홍']),
  ('shanks', array['샹크스']),
  ('tarzan', array['타잔','이승용']),
  ('bin', array['빈']),
  ('knight', array['나이트']),
  ('on', array['온']),
  ('viper', array['바이퍼']),
  ('xun', array['쉰']),
  ('feng', array['펑']),
  ('flauren', array['플로렌']),
  ('hongsuo', array['홍수오']),
  ('pop9', array['팝나인']),
  ('shiauc', array['샤오씨']),
  ('ayu', array['아유']),
  ('guigo', array['기고']),
  ('jojo', array['조조']),
  ('tatu', array['타투']),
  ('tutsz', array['투츠']),
  ('brokenblade', array['브로큰블레이드','브블']),
  ('caps', array['캡스']),
  ('hans-sama', array['한스사마']),
  ('labrov', array['라브로프']),
  ('skewmond', array['스큐몬드']),
  ('aress', array['아레스']),
  ('artemis', array['아르테미스']),
  ('draktharr', array['드락사르']),
  ('gloryy', array['글로리']),
  ('kiaya', array['키아야']),
  ('taki', array['타키']),
  ('gala', array['갈라']),
  ('hongq', array['홍큐']),
  ('junjia', array['준지아']),
  ('vampire', array['뱀파이어']),
  ('xiaoxu', array['샤오슈']),
  ('busio', array['부시오']),
  ('caliste', array['칼리스트']),
  ('canna', array['칸나']),
  ('kyeahoo', array['캬후']),
  ('yike', array['이케']),
  ('bull', array['불']),
  ('envy', array['엔비']),
  ('redbert', array['레드버트']),
  ('xyno', array['지노']),
  ('youngjae', array['영재']),
  ('berserker', array['버서커']),
  ('dhokla', array['도클라']),
  ('inspired', array['인스파이어드']),
  ('isles', array['아일즈']),
  ('saint', array['세인트']),
  ('alvaro', array['알바로']),
  ('elyoya', array['엘요야']),
  ('jojopyun', array['조조편']),
  ('myrwn', array['미른']),
  ('supa', array['수파']),
  ('ackerman', array['애커만']),
  ('curse', array['커스']),
  ('duduhh', array['두두']),
  ('feisty', array['피스티']),
  ('zest', array['제스트','김동민']),
  ('darkwings', array['다크윙스']),
  ('hambak', array['함박']),
  ('huhi', array['후히']),
  ('impact-sen', array['임팩트']),
  ('rahel', array['라헬']),
  ('creme', array['크림']),
  ('fengyue', array['펑위에']),
  ('jackeylove', array['재키러브']),
  ('tian', array['티안']),
  ('zuian', array['쭈이안']),
  ('corejj', array['코어장전','코어제이제이']),
  ('josedeodo', array['조세데오도']),
  ('morgan', array['모건']),
  ('quid', array['퀴드']),
  ('yeon', array['연']),
  ('bie', array['비에']),
  ('dire', array['다이어']),
  ('eddie', array['에디']),
  ('hizto', array['히즈토']),
  ('pun', array['펀'])
) as v(slug, aliases)
where p.slug = v.slug;

-- Teams: Korean names, common short forms, and legacy tags fans still search.
update public.teams t
set search_aliases = v.aliases
from (values
  ('agal', array['에이지에이엘']),
  ('bilibili-gaming', array['빌리빌리','비엘지']),
  ('fox', array['비엔케이','피어엑스','피어스']),
  ('deep-cross-gaming', array['딥크로스']),
  ('soop', array['수퍼스','디엔수퍼스','숲']),
  ('dk', array['디플러스기아','디플기아','디케이','담원']),
  ('furia', array['푸리아']),
  ('g2-esports', array['지투']),
  ('gam-esports', array['감이스포츠','감']),
  ('geng', array['젠지']),
  ('jd-gaming', array['제이디게이밍','제이디지']),
  ('karmine-corp', array['카민코프','카민']),
  ('drx', array['키움디알엑스','디알엑스','디렉스']),
  ('kt', array['케이티','케이티롤스터','롤스터']),
  ('loud', array['라우드']),
  ('lyon', array['리옹']),
  ('mibrlos', array['미브르']),
  ('movistar-koi', array['모비스타코이','코이']),
  ('sentinels', array['센티넬스']),
  ('t1', array['티원','티내원','에스케이티','skt','에스케이텔레콤']),
  ('team-liquid', array['팀리퀴드','리퀴드']),
  ('team-secret-whales', array['팀시크릿','시크릿웨일즈']),
  ('top-esports', array['탑이스포츠','탑e스포츠','탑']),
  ('ns', array['농심','레드포스','농심레드포스']),
  ('bro', array['브리온','한진브리온']),
  ('hle', array['한화생명','한화','한생'])
) as v(slug, aliases)
where t.slug = v.slug;
