with champion_catalog(ddragon_id, korean_name, slug, aliases) as (
  values
    ('Garen', '가렌', 'garen', array[]::text[]),
    ('Galio', '갈리오', 'galio', array[]::text[]),
    ('Gangplank', '갱플랭크', 'gangplank', array[]::text[]),
    ('Gragas', '그라가스', 'gragas', array[]::text[]),
    ('Graves', '그레이브즈', 'graves', array[]::text[]),
    ('Gwen', '그웬', 'gwen', array[]::text[]),
    ('Gnar', '나르', 'gnar', array[]::text[]),
    ('Nami', '나미', 'nami', array[]::text[]),
    ('Nasus', '나서스', 'nasus', array[]::text[]),
    ('Naafiri', '나피리', 'naafiri', array[]::text[]),
    ('Nautilus', '노틸러스', 'nautilus', array[]::text[]),
    ('Nocturne', '녹턴', 'nocturne', array[]::text[]),
    ('Nunu', '누누와 윌럼프', 'nunu', array['NunuWillump', 'Nunu Willump']::text[]),
    ('Nidalee', '니달리', 'nidalee', array[]::text[]),
    ('Neeko', '니코', 'neeko', array[]::text[]),
    ('Nilah', '닐라', 'nilah', array[]::text[]),
    ('Darius', '다리우스', 'darius', array[]::text[]),
    ('Diana', '다이애나', 'diana', array[]::text[]),
    ('Draven', '드레이븐', 'draven', array[]::text[]),
    ('Ryze', '라이즈', 'ryze', array[]::text[]),
    ('Rakan', '라칸', 'rakan', array[]::text[]),
    ('Rammus', '람머스', 'rammus', array[]::text[]),
    ('Lux', '럭스', 'lux', array[]::text[]),
    ('Rumble', '럼블', 'rumble', array[]::text[]),
    ('Renata', '레나타 글라스크', 'renata', array['RenataGlasc', 'Renata Glasc']::text[]),
    ('Renekton', '레넥톤', 'renekton', array[]::text[]),
    ('Leona', '레오나', 'leona', array[]::text[]),
    ('RekSai', '렉사이', 'rek-sai', array['Rek''Sai']::text[]),
    ('Rell', '렐', 'rell', array[]::text[]),
    ('Rengar', '렝가', 'rengar', array[]::text[]),
    ('Lucian', '루시안', 'lucian', array[]::text[]),
    ('Lulu', '룰루', 'lulu', array[]::text[]),
    ('Leblanc', '르블랑', 'leblanc', array['LeBlanc']::text[]),
    ('LeeSin', '리 신', 'lee-sin', array['Lee Sin']::text[]),
    ('Riven', '리븐', 'riven', array[]::text[]),
    ('Lissandra', '리산드라', 'lissandra', array[]::text[]),
    ('Lillia', '릴리아', 'lillia', array[]::text[]),
    ('MasterYi', '마스터 이', 'master-yi', array['Master Yi']::text[]),
    ('Maokai', '마오카이', 'maokai', array[]::text[]),
    ('Malzahar', '말자하', 'malzahar', array[]::text[]),
    ('Malphite', '말파이트', 'malphite', array[]::text[]),
    ('Mel', '멜', 'mel', array[]::text[]),
    ('Mordekaiser', '모데카이저', 'mordekaiser', array[]::text[]),
    ('Morgana', '모르가나', 'morgana', array[]::text[]),
    ('DrMundo', '문도 박사', 'dr-mundo', array['Dr Mundo', 'Dr. Mundo']::text[]),
    ('MissFortune', '미스 포츈', 'miss-fortune', array['Miss Fortune']::text[]),
    ('Milio', '밀리오', 'milio', array[]::text[]),
    ('Bard', '바드', 'bard', array[]::text[]),
    ('Varus', '바루스', 'varus', array[]::text[]),
    ('Vi', '바이', 'vi', array[]::text[]),
    ('Veigar', '베이가', 'veigar', array[]::text[]),
    ('Vayne', '베인', 'vayne', array[]::text[]),
    ('Vex', '벡스', 'vex', array[]::text[]),
    ('Belveth', '벨베스', 'belveth', array['BelVeth', 'Bel''Veth']::text[]),
    ('Velkoz', '벨코즈', 'velkoz', array['VelKoz', 'Vel''Koz']::text[]),
    ('Volibear', '볼리베어', 'volibear', array[]::text[]),
    ('Braum', '브라움', 'braum', array[]::text[]),
    ('Briar', '브라이어', 'briar', array[]::text[]),
    ('Brand', '브랜드', 'brand', array[]::text[]),
    ('Vladimir', '블라디미르', 'vladimir', array[]::text[]),
    ('Blitzcrank', '블리츠크랭크', 'blitzcrank', array[]::text[]),
    ('Viego', '비에고', 'viego', array[]::text[]),
    ('Viktor', '빅토르', 'viktor', array[]::text[]),
    ('Poppy', '뽀삐', 'poppy', array[]::text[]),
    ('Samira', '사미라', 'samira', array[]::text[]),
    ('Sion', '사이온', 'sion', array[]::text[]),
    ('Sylas', '사일러스', 'sylas', array[]::text[]),
    ('Shaco', '샤코', 'shaco', array[]::text[]),
    ('Senna', '세나', 'senna', array[]::text[]),
    ('Seraphine', '세라핀', 'seraphine', array[]::text[]),
    ('Sejuani', '세주아니', 'sejuani', array[]::text[]),
    ('Sett', '세트', 'sett', array[]::text[]),
    ('Sona', '소나', 'sona', array[]::text[]),
    ('Soraka', '소라카', 'soraka', array[]::text[]),
    ('Shen', '쉔', 'shen', array[]::text[]),
    ('Shyvana', '쉬바나', 'shyvana', array[]::text[]),
    ('Smolder', '스몰더', 'smolder', array[]::text[]),
    ('Swain', '스웨인', 'swain', array[]::text[]),
    ('Skarner', '스카너', 'skarner', array[]::text[]),
    ('Sivir', '시비르', 'sivir', array[]::text[]),
    ('XinZhao', '신 짜오', 'xin-zhao', array['Xin Zhao']::text[]),
    ('Syndra', '신드라', 'syndra', array[]::text[]),
    ('Singed', '신지드', 'singed', array[]::text[]),
    ('Thresh', '쓰레쉬', 'thresh', array[]::text[]),
    ('Ahri', '아리', 'ahri', array[]::text[]),
    ('Amumu', '아무무', 'amumu', array[]::text[]),
    ('AurelionSol', '아우렐리온 솔', 'aurelion-sol', array['Aurelion Sol']::text[]),
    ('Ivern', '아이번', 'ivern', array[]::text[]),
    ('Azir', '아지르', 'azir', array[]::text[]),
    ('Akali', '아칼리', 'akali', array[]::text[]),
    ('Akshan', '아크샨', 'akshan', array[]::text[]),
    ('Aatrox', '아트록스', 'aatrox', array[]::text[]),
    ('Aphelios', '아펠리오스', 'aphelios', array[]::text[]),
    ('Alistar', '알리스타', 'alistar', array[]::text[]),
    ('Ambessa', '암베사', 'ambessa', array[]::text[]),
    ('Annie', '애니', 'annie', array[]::text[]),
    ('Anivia', '애니비아', 'anivia', array[]::text[]),
    ('Ashe', '애쉬', 'ashe', array[]::text[]),
    ('Yasuo', '야스오', 'yasuo', array[]::text[]),
    ('Ekko', '에코', 'ekko', array[]::text[]),
    ('Elise', '엘리스', 'elise', array[]::text[]),
    ('MonkeyKing', '오공', 'monkey-king', array['Wukong']::text[]),
    ('Aurora', '오로라', 'aurora', array[]::text[]),
    ('Ornn', '오른', 'ornn', array[]::text[]),
    ('Orianna', '오리아나', 'orianna', array[]::text[]),
    ('Olaf', '올라프', 'olaf', array[]::text[]),
    ('Yone', '요네', 'yone', array[]::text[]),
    ('Yorick', '요릭', 'yorick', array[]::text[]),
    ('Yunara', '유나라', 'yunara', array[]::text[]),
    ('Udyr', '우디르', 'udyr', array[]::text[]),
    ('Urgot', '우르곳', 'urgot', array[]::text[]),
    ('Warwick', '워윅', 'warwick', array[]::text[]),
    ('Yuumi', '유미', 'yuumi', array[]::text[]),
    ('Irelia', '이렐리아', 'irelia', array[]::text[]),
    ('Evelynn', '이블린', 'evelynn', array[]::text[]),
    ('Ezreal', '이즈리얼', 'ezreal', array[]::text[]),
    ('Illaoi', '일라오이', 'illaoi', array[]::text[]),
    ('JarvanIV', '자르반 4세', 'jarvan-iv', array['Jarvan IV']::text[]),
    ('Xayah', '자야', 'xayah', array[]::text[]),
    ('Zyra', '자이라', 'zyra', array[]::text[]),
    ('Zac', '자크', 'zac', array[]::text[]),
    ('Zaahen', '자헨', 'zaahen', array[]::text[]),
    ('Janna', '잔나', 'janna', array[]::text[]),
    ('Jax', '잭스', 'jax', array[]::text[]),
    ('Zed', '제드', 'zed', array[]::text[]),
    ('Xerath', '제라스', 'xerath', array[]::text[]),
    ('Zeri', '제리', 'zeri', array[]::text[]),
    ('Jayce', '제이스', 'jayce', array[]::text[]),
    ('Zoe', '조이', 'zoe', array[]::text[]),
    ('Ziggs', '직스', 'ziggs', array[]::text[]),
    ('Jhin', '진', 'jhin', array[]::text[]),
    ('Zilean', '질리언', 'zilean', array[]::text[]),
    ('Jinx', '징크스', 'jinx', array[]::text[]),
    ('Chogath', '초가스', 'chogath', array['ChoGath', 'Cho''Gath']::text[]),
    ('Karma', '카르마', 'karma', array[]::text[]),
    ('Camille', '카밀', 'camille', array[]::text[]),
    ('Kassadin', '카사딘', 'kassadin', array[]::text[]),
    ('Karthus', '카서스', 'karthus', array[]::text[]),
    ('Cassiopeia', '카시오페아', 'cassiopeia', array[]::text[]),
    ('Kaisa', '카이사', 'kaisa', array['KaiSa', 'Kai''Sa', 'kai-sa']::text[]),
    ('Khazix', '카직스', 'khazix', array['KhaZix', 'Kha''Zix', 'kha-zix']::text[]),
    ('Katarina', '카타리나', 'katarina', array[]::text[]),
    ('Kalista', '칼리스타', 'kalista', array[]::text[]),
    ('Kennen', '케넨', 'kennen', array[]::text[]),
    ('Caitlyn', '케이틀린', 'caitlyn', array[]::text[]),
    ('Kayn', '케인', 'kayn', array[]::text[]),
    ('Kayle', '케일', 'kayle', array[]::text[]),
    ('KogMaw', '코그모', 'kog-maw', array['Kog Maw', 'Kog''Maw']::text[]),
    ('Corki', '코르키', 'corki', array[]::text[]),
    ('Quinn', '퀸', 'quinn', array[]::text[]),
    ('KSante', '크산테', 'ksante', array['Ksante', 'K''Sante']::text[]),
    ('Kled', '클레드', 'kled', array[]::text[]),
    ('Qiyana', '키아나', 'qiyana', array[]::text[]),
    ('Kindred', '킨드레드', 'kindred', array[]::text[]),
    ('Taric', '타릭', 'taric', array[]::text[]),
    ('Talon', '탈론', 'talon', array[]::text[]),
    ('Taliyah', '탈리야', 'taliyah', array[]::text[]),
    ('TahmKench', '탐 켄치', 'tahm-kench', array['Tahm Kench']::text[]),
    ('Trundle', '트런들', 'trundle', array[]::text[]),
    ('Tristana', '트리스타나', 'tristana', array[]::text[]),
    ('Tryndamere', '트린다미어', 'tryndamere', array[]::text[]),
    ('TwistedFate', '트위스티드 페이트', 'twisted-fate', array['Twisted Fate']::text[]),
    ('Twitch', '트위치', 'twitch', array[]::text[]),
    ('Teemo', '티모', 'teemo', array[]::text[]),
    ('Pyke', '파이크', 'pyke', array[]::text[]),
    ('Pantheon', '판테온', 'pantheon', array[]::text[]),
    ('Fiddlesticks', '피들스틱', 'fiddlesticks', array['Fiddle Sticks']::text[]),
    ('Fiora', '피오라', 'fiora', array[]::text[]),
    ('Fizz', '피즈', 'fizz', array[]::text[]),
    ('Heimerdinger', '하이머딩거', 'heimerdinger', array[]::text[]),
    ('Hecarim', '헤카림', 'hecarim', array[]::text[]),
    ('Hwei', '흐웨이', 'hwei', array[]::text[])
),
champion_catalog_keys as (
  select
    ddragon_id,
    korean_name,
    regexp_replace(lower(key), '[^a-z0-9]', '', 'g') as match_key
  from champion_catalog
  cross join lateral unnest(array[ddragon_id, slug, korean_name] || aliases) as key
)
update public.champions as champions
set
  name = champion_catalog_keys.korean_name,
  ddragon_id = champion_catalog_keys.ddragon_id
from champion_catalog_keys
where regexp_replace(
  lower(coalesce(champions.ddragon_id, champions.slug, champions.name)),
  '[^a-z0-9]',
  '',
  'g'
) = champion_catalog_keys.match_key;
